#!/usr/bin/env python3
import os
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

import Screenote.systray as st

def main():
    Gtk.init()
    app = st.SystemTrayIcon()
    Gtk.main()


if __name__ == "__main__":
    main()
